kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployments
spec:
   replicas: 2
   selector:      
    matchLabels:
     name: deployment
   template:
     metadata:
       name: testpod
       labels:
         name: deployment
     spec:
      containers:
        - name: apache
          image: httpd
          ports:
           - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: demoservice
spec:
  ports:
    - port: 80           
      targetPort: 80
  selector:
    name: deployment
  clusterIP: None
