kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployments
spec:
   replicas: 2
   selector:     
    matchLabels:
     name: deployment
   template:
     metadata:
       name: testpod
       labels:
         name: deployment
     spec:
      containers:
        - name: myapl
          image: amiyaranjansahoo/myapp:v1
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: demoservice
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: deployment
  type: LoadBalancer
---
###kammana/nodeapp:v1
---
apiVersion: v1
kind: Service
metadata:
  name: demoservice
  labels:
    app: demoservice
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # To create Network Load Balancer
spec:
  type: LoadBalancer
  selector:
    name: deployment     
  ports:
  - port: 80
    targetPort: 8080
