kind: Deployment
apiVersion: apps/v1
metadata:
   name: prod
spec:
   replicas: 1
   selector:     
    matchLabels:
     app: prod
   template:
     metadata:
       labels:
         app: prod
     spec:
      containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo welcome to k8s Deployment; sleep 5; done"]
      tolerations:
      - key: node-type
        operator: Equal
        value: prod
        effect: NoSchedule
