apiVersion: v1
kind: Pod
metadata:
  name: myvolemptydir
spec:
  containers:
  - name: centos1
    image: centos
    command: ["/bin/bash", "-c", "sleep 15000"]
    volumeMounts:                 
      - name: xchange
        mountPath: "/xchange"          
  - name: centos2
    image: centos
    command: ["/bin/bash", "-c", "sleep 10000"]
    volumeMounts:
      - name: xchange
        mountPath: "/tmp/data"
  volumes:                                                   
  - name: xchange
    emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployments
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: c1
          image: centos
          command: ["/bin/bash", "-c", "sleep 15000"]
          volumeMounts:                  # Mount definition inside the container
            - name: xchange
              mountPath: "/tmp/xchange"          
        - name: c2
          image: centos
          command: ["/bin/bash", "-c", "sleep 10000"]
          volumeMounts:
            - name: xchange
              mountPath: "/tmp/data"
      volumes:                                                   
        - name: xchange
          emptyDir: {}
