startupProbe:
  httpGet:
    path: /healthz
  failureThreshold: 30
  periodSeconds: 10
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx-container
      image: amiyaranjansahoo/myapp:v1
      ports:
        - containerPort: 8080
      startupProbe:
        httpGet:
          path: /
          port: 8080
        periodSeconds: 10          
        failureThreshold: 10
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: mylivenessprobe
spec:
  containers:
  - name: liveness
    image: ubuntu
    command: ["/bin/sh","-c","touch /tmp/healthy; sleep 1000"]
    startupProbe:
      exec:
        command: ["/bin/sh","-c","cat /etc/foo"]
      periodSeconds: 2
      failureThreshold: 2
