apiVersion: v1
kind: Pod
metadata:
  name: nginx1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - { key: disktype , operator: In , values: [ ssd ] }            
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent

---


apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
           - { key: disktype ,  operator: In ,  values: [ ssd ] }          
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
